### ISSUE TITLE
Changes to options in the Options dialog box are not used

### ISSUE THREAD

**Issue by CyberBotX** [HO-COOH/ResourceMonitor#2]
For example, if I set "Show CPU Usage" to False and then click OK in Options, the CPU Usage still shows up. Same for all the other boolean values. Changing the units for the RAM usage don't change it away from using MB for Visual Studio's RAM usage or GB for total system RAM usage. Changing the refresh rate doesn't affect the refresh rate, it still updates every 1 second.

I cannot see why this would be the case from glancing through the source code, as it appears it should be working.

I am using Visual Studio 2022, a completely fresh install prior to the installation of ResourceMonitor.

**Comment by HO-COOH** [comment]
Thanks for reporting. Indeed this seems to be the case. I just ported this visual studio 2022 without much testing because those are my default settings. I remembered testing it in 2019 and it's working fine. I will look into this some time

**Comment by KyleKolander** [comment]
Cool extension, but I'm also running into this.  I use a desktop computer, so have no use for the Battery values.  It would be cool if you could fix this.

**Comment by HO-COOH** [comment]
Fixed, please update! This is due to a change in VS2022 caching the OptionsDialog instance.

**Comment by KyleKolander** [comment]
Thanks!  Works like a charm!

**Comment by CyberBotX** [comment]
I never got around to replying, but the issue is indeed fixed, thanks for the update!
